#!/usr/bin/env python
import sys, shlex

out = ""

todo = open("todo", "r")

for line in todo:
	if ! line.startswith("---"):
		out += line
	else: # we have read in everything above a ---- by now
		# keep the ----
		newtodo = (line + "".join(todo))
		open("todo", "w").write(newtodo)
		
		args = os.args[1:]
		os.system("git commit " + " ".join(args) + " -m \"" + shlex.quote(out) + "\"")
		


