#!/usr/bin/env python
import sys

template_filename = sys.argv[1]
template_file = open(template_filename, "r")

nonempty = [line for line in template_file if len(line) > 0 and line[0] not in ("#","\n")]

if nonempty != []:
	print "there is/are already nonempty lines in %s :%s, (probably from git commit -m) will not use the todo file, bye"%(template_filename, nonempty) 
	exit() 

template_file.seek(0)

out = ""

todo = open("todo", "r")

for line in todo:
	if line != "----\n":
		out += line
	else: # we have read in everything above a ---- by now
		out = out + template_file.read()
		open(template_filename, "w").write(out)
		newtodo = (line + # keep the ---- line
			 "".join(todo))
		open("todo", "w").write(newtodo)



