#!/usr/bin/env python
import sys

out = ""
msg = sys.argv[1]
todo = open("todo", "r").xreadlines()

for line in todo:
	if line != "----\n":
		out += line
	else:
		out = out + open(msg, "r").read()
		open(msg, "w").write(out)
		newtodo = line + "".join(todo)
		open("todo", "w").write(newtodo)



