# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class MenuGuiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.noticeThatServerDataChanged = channel.unary_unary(
        '/lemon.MenuGui/noticeThatServerDataChanged',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class MenuGuiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def noticeThatServerDataChanged(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MenuGuiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'noticeThatServerDataChanged': grpc.unary_unary_rpc_method_handler(
          servicer.noticeThatServerDataChanged,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'lemon.MenuGui', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
